### ISSUE TITLE
Add a release route. Refactor a sourcemap route.

### ISSUE THREAD

**Issue by GeekaN2** [codex-team/hawk.collector#75]
You need to create a new route `/release` that will accept the release data and will include the source maps.
https://docs.codex.so/suspected-commits#izmeneniya-v-kollektore

**Comment by n0str** [comment]
Could you provide a sample structure of message that will go to collector (export from insomnia/or other REST client) and sample message that collector has to send to the Queue. Which queue?

**Comment by GeekaN2** [comment]
We need to add the task to the `source-map` worker (I'll rename it to `release`). The payload interfaces are here
https://github.com/codex-team/hawk.workers/blob/suspected-commits/workers/source-maps/types/sender-task/add-release.ts
